services:
  ss-azure-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss-azure-dev
    user: node
    volumes:
      - .:/workspace
      - pnpm-store:/home/node/.local/share/pnpm/store
      - pulumi-config:/home/node/.pulumi
      - azure-config:/home/node/.azure
      - aws-config:/home/node/.aws
    environment:
      NODE_ENV: development
      PULUMI_SKIP_UPDATE_CHECK: "true"
      PNPM_HOME: /home/node/.local/share/pnpm
      PATH: /home/node/.local/share/pnpm:$PATH
      DATABASE_URL: postgresql://ssuser:development@ss-azure-postgres:5432/ssdb?schema=public
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      - "3000:5173"
      - "8002:8002"
      - "5555:5555"
    networks:
      - ss-azure-network

  ss-azure-postgres:
    image: postgres:15-alpine
    container_name: ss-azure-postgres
    environment:
      POSTGRES_USER: ssuser
      POSTGRES_PASSWORD: development
      POSTGRES_DB: ssdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ss-azure-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pnpm-store:
  pulumi-config:
  azure-config:
  aws-config:
  postgres-data:

networks:
  ss-azure-network:
    driver: bridge
