services:
  ss-azure-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss-azure-dev
    user: node
    volumes:
      # プロジェクト全体をマウント
      - .:/workspace
      # pnpm のキャッシュを永続化
      - pnpm-store:/home/node/.local/share/pnpm/store
      # Pulumi の設定を永続化
      - pulumi-config:/home/node/.pulumi
      # Azure CLI の設定を永続化
      - azure-config:/home/node/.azure
      # AWS CLI の設定を永続化
      - aws-config:/home/node/.aws
    environment:
      # Node.js 環境変数
      NODE_ENV: development
      # Pulumi 環境変数
      PULUMI_SKIP_UPDATE_CHECK: "true"
      # pnpm の設定
      PNPM_HOME: /home/node/.local/share/pnpm
      PATH: /home/node/.local/share/pnpm:$PATH
    working_dir: /workspace
    tty: true
    stdin_open: true
    ports:
      # Remix 開発サーバー (Vite)
      - "3000:5173"
      # Remix WebSocket (HMR)
      - "8002:8002"
    networks:
      - ss-azure-network

  # ローカル開発用の PostgreSQL（オプション）
  ss-azure-postgres:
    image: postgres:15-alpine
    container_name: ss-azure-postgres
    environment:
      POSTGRES_USER: ssuser
      POSTGRES_PASSWORD: development
      POSTGRES_DB: ssdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ss-azure-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssuser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pnpm-store:
  pulumi-config:
  azure-config:
  aws-config:
  postgres-data:

networks:
  ss-azure-network:
    driver: bridge