name: Build and Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  REGISTRY_NAME: ssazurestagingacr
  IMAGE_NAME: ss-azure-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        file: ./app/Dockerfile.production
        push: true
        tags: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        platforms: linux/amd64

    - name: Update Container Instance in VNet
      run: |
        # VNet内のContainer Instancesを新しいイメージで更新
        # 既存のContainer Instancesを削除
        az container delete \
          --name ss-azure-staging-container-vnet \
          --resource-group ss-azure-staging-rg \
          --yes \
          --no-wait || true
        
        # 少し待機（削除処理のため）
        sleep 10
        
        # VNet内にContainer Instancesを作成
        az container create \
          --resource-group ss-azure-staging-rg \
          --name ss-azure-staging-container-vnet \
          --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --registry-login-server ${{ env.REGISTRY_NAME }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --subnet ${{ secrets.VNET_SUBNET_ID }} \
          --os-type Linux \
          --cpu 1 \
          --memory 1.5 \
          --restart-policy Always \
          --ip-address Private \
          --ports 80 \
          --environment-variables \
            NODE_ENV=production \
            PORT=80 \
            DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            APPLICATIONINSIGHTS_CONNECTION_STRING="${{ secrets.APP_INSIGHTS_CONNECTION_STRING }}" \
          --location japaneast \
          --no-wait \
          || echo "Container update initiated"
      continue-on-error: true
    
    - name: Update Application Gateway Backend
      run: |
        # Container InstancesのプライベートIPを取得
        CONTAINER_IP=$(az container show \
          --name ss-azure-staging-container-vnet \
          --resource-group ss-azure-staging-rg \
          --query "ipAddress.ip" -o tsv) || echo "10.0.1.5"
        
        echo "Container IP: $CONTAINER_IP"
        
        # Application Gatewayのバックエンドプールを更新
        if [ ! -z "$CONTAINER_IP" ]; then
          az network application-gateway address-pool update \
            --gateway-name ss-azure-staging-appgw \
            --resource-group ss-azure-staging-rg \
            --name backend-pool \
            --servers $CONTAINER_IP \
            --no-wait || true
        fi
      continue-on-error: true