name: Run Database Migrations via Container

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to migrate'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  migrate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run migrations in Container Instance
        run: |
          echo "Running Prisma migrations for ${{ inputs.environment }} environment..."
          
          # Container Instance内でマイグレーションを実行
          echo "Executing migrations in Container Instance..."
          
          az container exec \
            --name ss-azure-staging-container-vnet \
            --resource-group ss-azure-staging-rg \
            --container-name ss-azure-staging-container-vnet \
            --exec-command "sh -c 'cd /app && npx prisma migrate status && npx prisma migrate deploy && echo Migration completed successfully'" \
            || { echo "Migration execution failed"; exit 1; }
          
          echo "Migrations completed successfully for ${{ inputs.environment }}"
      
      - name: Verify migration status
        run: |
          echo "Verifying migration status..."
          
          az container exec \
            --name ss-azure-staging-container-vnet \
            --resource-group ss-azure-staging-rg \
            --container-name ss-azure-staging-container-vnet \
            --exec-command "sh -c 'cd /app && npx prisma migrate status'" \
            || echo "Status check failed (non-critical)"